enum FileType {
    APPLICATION_PDF='APPLICATION_PDF',
    IDENTIFICATION_PDF='IDENTIFICATION_PDF',
    FORM='FORM',
    PROFILE_PICTURE='PROFILE_PICTURE',
    MISC='MISC',
    ORG_DOCUMENT='ORG_DOCUMENT'
}

export default FileType;
