name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: workflows/checkout@v1
      - name: Set up JDK 13
        uses: workflows/setup-java@v1
        with:
          java-version: 13
      - name: Build with Maven
        run: mvn -B package --file pom.xml
